/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package JsonDocletJava8

import kotlin.test.Test
import kotlin.test.assertTrue

class DocletTest {
    @Test fun testExample() {
        assertTrue(true)
    }
}
