/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.yokedox

import com.sun.source.util.DocTrees
import java.util.*
import javax.lang.model.SourceVersion
import jdk.javadoc.doclet.*

lateinit var docTrees: DocTrees

/**
 * A doclet for creating a manifest json file of available code examples for the entities in the project.
 */
class JsonDoclet : Doclet {
  override fun init(locale: Locale?, reporter: Reporter?) {
  }

  override fun getName(): String {
    return "JsonDoclet"
  }

  override fun getSupportedOptions(): Set<Doclet.Option> {
    return HashSet()
  }

  override fun getSupportedSourceVersion(): SourceVersion {
    return SourceVersion.RELEASE_9
  }

  override fun run(environment: DocletEnvironment): Boolean {
    docTrees = environment.docTrees
    val root = toJson(environment)
    println(root.toString())
    return true
  }
}
