/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.yokedox

import java.util.*
import javax.lang.model.SourceVersion
import jdk.javadoc.doclet.*

/**
 * A doclet for creating a manifest json file of available code examples for the entities in the project.
 */
class JsonDoclet : Doclet {
    override fun init(locale: Locale?, reporter: Reporter?) {
    }

    override fun getName(): String {
        return "JsonDoclet"
    }

    override fun getSupportedOptions(): Set<Doclet.Option> {
        val options = HashSet<Doclet.Option>()
        return options
    }

    override fun getSupportedSourceVersion(): SourceVersion {
        return SourceVersion.RELEASE_0
    }

    override fun run(docEnv: DocletEnvironment?): Boolean {
        System.out.println("Chbus it owrks!")
        return true
    }
}
