/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.yokedox

import org.junit.Test
import org.junit.Assert.*

class JsonValueTest {
  @Test fun testValueEquality() {
    assertEquals(JsonValue(null), null)
    assertEquals(JsonValue(1), 1)
    assertEquals(JsonValue(1.023), 1.023)
    assertEquals(JsonValue(1e-10), 1e-10)
    assertEquals(JsonValue(-20), -20)
    assertEquals(JsonValue(true), true)
    assertEquals(JsonValue(false), false)
    assertEquals(JsonValue("something"), "something")
    assertEquals(JsonValue(mapOf(
      "a" to 1
    )), mapOf(
      "a" to 1
    ))
    assertEquals(JsonValue(listOf(
      1, "a", false
    )), listOf(1, "a", false))


  }

  @Test fun testArrayToString() {
    val array = JsonValue(listOf(
      1,
      "some \" string",
      1e-13,
      JsonValue(1.02),
      JsonValue(true)
    ))
    assertEquals("""[1, "some \" string", 1.0E-13, 1.02, true]""", array.toString())
  }

  @Test fun testObjectToString() {
    val obj = JsonValue(mapOf<String, JsonValue>(
      "one" to JsonValue(1),
      "some string" to JsonValue("some \" string"),
      "small number" to JsonValue(1e-13),
      "float" to JsonValue(1.02),
      "true" to JsonValue(true),
      "null" to JsonValue(null),
      "array" to JsonValue(listOf(
        JsonValue(1),
        JsonValue(2),
        JsonValue(3)
      ))
    ))
    assertEquals("""{"one": 1, "some string": "some \" string", "small number": 1.0E-13, "float": 1.02, "true": true, "null": null, "array": [1, 2, 3]}""", obj.toString())
  }
}
